# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_number", models.CharField(max_length=100)),
                ("carrier", models.CharField(blank=True, max_length=255)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("bill_of_lading", models.CharField(blank=True, max_length=100)),
                ("estimated_departure_date", models.DateField(blank=True, null=True)),
                ("actual_departure_date", models.DateField(blank=True, null=True)),
                ("estimated_arrival_date", models.DateField(blank=True, null=True)),
                ("actual_arrival_date", models.DateField(blank=True, null=True)),
                ("port_of_origin", models.CharField(blank=True, max_length=255)),
                ("port_of_destination", models.CharField(blank=True, max_length=255)),
                ("customs_cleared_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-estimated_arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "performance_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Rating from 1-5",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSU", "Issued"),
                            ("ACKN", "Acknowledged"),
                            ("PREC", "Partially Received"),
                            ("COMP", "Complete"),
                            ("CANC", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "incoterms",
                    models.CharField(
                        blank=True, help_text="e.g., 'FOB', 'CIF', 'EXW'", max_length=50
                    ),
                ),
                ("shipping_method", models.CharField(blank=True, max_length=100)),
                ("payment_terms", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="core.project",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="procurement.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_item_number", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        default="EA", help_text="EA, M, KG, LOT", max_length=20
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("required_on_site_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("is_received", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
                "ordering": ["purchase_order", "line_item_number"],
                "unique_together": {("purchase_order", "line_item_number")},
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_shipped",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_received", models.BooleanField(default=False)),
                ("packing_list_number", models.CharField(blank=True, max_length=100)),
                (
                    "condition_on_arrival",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Good', 'Damaged', 'Incomplete'",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="procurement.purchaseorderitem",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Item",
                "verbose_name_plural": "Shipment Items",
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="procurement.supplier",
            ),
        ),
    ]
