# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstalledItemCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_date", models.DateField()),
                ("foundation_ok", models.BooleanField(null=True)),
                ("grouting_ok", models.BooleanField(null=True)),
                ("bolting_ok", models.BooleanField(null=True)),
                ("alignment_ok", models.BooleanField(null=True)),
                ("electrical_ok", models.BooleanField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail with Punch List"),
                            ("NA", "Not Applicable"),
                        ],
                        default="PASS",
                        max_length=4,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installation_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installation_checks",
                        to="core.equipmenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installed Item Check",
                "verbose_name_plural": "Installed Item Checks",
                "ordering": ["-checked_date"],
            },
        ),
        migrations.CreateModel(
            name="InstallationCheckPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="installation_photos/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installation_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="construction.installeditemcheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installation Check Photo",
                "verbose_name_plural": "Installation Check Photos",
            },
        ),
        migrations.CreateModel(
            name="WorkPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        help_text="Company executing the work",
                        max_length=255,
                    ),
                ),
                ("planned_start", models.DateField()),
                ("planned_finish", models.DateField()),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_finish", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NSTA", "Not Started"),
                            ("MOB", "Mobilizing"),
                            ("IPRO", "In Progress"),
                            ("COMP", "Complete"),
                            ("HOLD", "On Hold"),
                        ],
                        default="NSTA",
                        max_length=4,
                    ),
                ),
                (
                    "percent_complete",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="1=Highest, 5=Lowest"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_packages",
                        to="core.area",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_packages",
                        to="core.project",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_work_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_packages",
                        to="core.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Package",
                "verbose_name_plural": "Work Packages",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DailyProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("work_performed_description", models.TextField()),
                ("issues_encountered", models.TextField(blank=True)),
                ("weather_conditions", models.CharField(blank=True, max_length=200)),
                ("temperature_celsius", models.IntegerField(blank=True, null=True)),
                ("manpower_count", models.PositiveIntegerField(default=0)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="construction.workpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Progress Report",
                "verbose_name_plural": "Daily Progress Reports",
                "ordering": ["-report_date"],
                "unique_together": {("work_package", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="WorkPackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Order of installation"
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_package_items",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="construction.workpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Package Item",
                "verbose_name_plural": "Work Package Items",
                "ordering": ["sequence_number"],
                "unique_together": {("work_package", "equipment_tag")},
            },
        ),
    ]
