# Generated by Django 6.0.6 on 2026-07-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProccessReportEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_working", models.BooleanField(default=False)),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="construction.dailyprogressreport",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_employees",
                        to="resources.employee",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="resources.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Proccess Report Employee",
                "verbose_name_plural": "Daily Proccess Report Employees",
                "ordering": ["employee", "daily_report"],
                "unique_together": {("employee", "daily_report")},
            },
        ),
    ]
