# Generated by Django 6.0.6 on 2026-08-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0002_dailyproccessreportemployees"),
        ("resources", "0002_alter_timesheet_date_alter_timesheet_hours_worked"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProcessReportEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_working", models.BooleanField(default=False)),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="construction.dailyprogressreport",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_employees",
                        to="resources.employee",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_reports",
                        to="resources.timesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Process Report Employee",
                "verbose_name_plural": "Daily Process Report Employees",
                "ordering": ["employee", "daily_report"],
                "unique_together": {("employee", "daily_report")},
            },
        ),
        migrations.DeleteModel(
            name="DailyProccessReportEmployees",
        ),
    ]
