# Generated by Django 6.0.6 on 2026-08-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0003_dailyprocessreportemployees_and_more"),
        ("resources", "0004_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprogressreport",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="resources.company",
            ),
        ),
    ]
