# Generated by Django 6.0.6 on 2026-08-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0004_dailyprogressreport_company"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyprogressreport",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workpackageitem",
            unique_together=set(),
        ),
    ]
