# Generated by Django 6.0.6 on 2026-08-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0005_alter_dailyprogressreport_unique_together_and_more"),
        ("core", "0005_equipmenttag_drawing_num"),
        ("resources", "0006_employee_contractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackage",
            name="contractor_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_packages",
                to="resources.company",
            ),
        ),
        migrations.AlterField(
            model_name="workpackage",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_packages",
                to="core.area",
            ),
        ),
    ]
