# Generated by Django 6.0.6 on 2026-08-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0006_workpackage_contractor_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkpackageRequirments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("priority", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "work_pack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="construction.workpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Package Requirements",
                "verbose_name_plural": "Work Package Requirements",
            },
        ),
    ]
