# Generated by Django 6.0.6 on 2026-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0007_workpackagerequirments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkpackageRequirments",
            new_name="WorkPackageRequirements",
        ),
    ]
