# Generated by Django 6.0.6 on 2026-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0008_rename_workpackagerequirments_workpackagerequirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackagerequirements",
            name="is_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
