# Generated by Django 6.0.6 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0009_workpackagerequirements_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackage",
            name="level",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
