# Generated by Django 6.0.6 on 2026-08-29 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0010_workpackage_level"),
        ("core", "0010_equipmenttag_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpackageitem",
            name="equipment_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_package_items",
                to="core.equipmenttag",
            ),
        ),
        migrations.AlterField(
            model_name="workpackageitem",
            name="work_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="construction.workpackage",
            ),
        ),
    ]
