# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("construction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_number", models.CharField(max_length=100, unique=True)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("CRANE", "Mobile Crane"),
                            ("TWRN", "Tower Crane"),
                            ("FORK", "Forklift"),
                            ("WELD", "Welding Machine"),
                            ("GEN", "Generator"),
                            ("COMP", "Compressor"),
                            ("PUMP", "Pump"),
                            ("LITE", "Lighting Plant"),
                            ("OTHR", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "capacity",
                    models.CharField(
                        blank=True, help_text="e.g., '100T', '500kVA'", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVL", "Available"),
                            ("INUS", "In Use"),
                            ("DOWN", "Down for Maintenance"),
                            ("REPR", "Needs Repair"),
                            ("RETD", "Retired"),
                        ],
                        default="AVL",
                        max_length=4,
                    ),
                ),
                ("current_location", models.CharField(blank=True, max_length=255)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tool/Plant",
                "verbose_name_plural": "Tools/Plant",
                "ordering": ["tool_type", "asset_number"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "company",
                    models.CharField(
                        help_text="Contractor or employer name", max_length=255
                    ),
                ),
                (
                    "trade",
                    models.CharField(
                        choices=[
                            ("MLWR", "Millwright"),
                            ("ELEC", "Electrician"),
                            ("WELD", "Welder"),
                            ("PIPE", "Pipe Fitter"),
                            ("INST", "Instrument Technician"),
                            ("RIGG", "Rigger"),
                            ("SUPV", "Supervisor"),
                            ("ENGR", "Engineer"),
                            ("SAFE", "Safety Officer"),
                            ("LAB", "Laborer"),
                            ("OPER", "Operator"),
                            ("OTHR", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuing_body", models.CharField(blank=True, max_length=255)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "document_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/%Y/%m/%d/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="resources.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="ToolAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_start", models.DateTimeField()),
                ("assignment_end", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_assignments",
                        to="construction.workpackage",
                    ),
                ),
                (
                    "tool_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="resources.toolplant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Assignment",
                "verbose_name_plural": "Tool Assignments",
                "ordering": ["-assignment_start"],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_worked", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="resources.employee",
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="construction.workpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timesheet",
                "verbose_name_plural": "Timesheets",
                "ordering": ["-date"],
                "unique_together": {("employee", "work_package", "date")},
            },
        ),
    ]
