# Generated by Django 6.0.6 on 2026-08-02 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="hours_worked",
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4),
        ),
    ]
