# Generated by Django 6.0.6 on 2026-08-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0003_dailyprocessreportemployees_and_more"),
        ("resources", "0002_alter_timesheet_date_alter_timesheet_hours_worked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="work_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheets",
                to="construction.workpackage",
            ),
        ),
    ]
