# Generated by Django 6.0.6 on 2026-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_timesheet_work_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
