# Generated by Django 6.0.6 on 2026-08-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["title"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
