# Generated by Django 6.0.6 on 2026-08-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="contractor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources.company",
            ),
        ),
    ]
