# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissioningSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREC", "Pre-Commissioning"),
                            ("COLD", "Cold Commissioning"),
                            ("HOT", "Hot Commissioning"),
                            ("RAMP", "Ramp-Up"),
                            ("PERF", "Performance Test"),
                            ("HNDO", "Handed Over"),
                        ],
                        default="PREC",
                        max_length=4,
                    ),
                ),
                ("planned_start", models.DateField()),
                ("planned_finish", models.DateField()),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_finish", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_engineer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_commissioning",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissioning_phases",
                        to="core.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commissioning System",
                "verbose_name_plural": "Commissioning Systems",
            },
        ),
        migrations.CreateModel(
            name="PunchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punch_number", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("raised_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("A", "A - Critical (Safety/Operations)"),
                            ("B", "B - Required before Handover"),
                            ("C", "C - Cosmetic/Minor"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "assigned_to_contractor",
                    models.CharField(blank=True, max_length=255),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("verified_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IPRO", "In Progress"),
                            ("RESL", "Resolved"),
                            ("CLSD", "Verified Closed"),
                            ("REJ", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_punch_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_items",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_items",
                        to="core.project",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raised_punch_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_items",
                        to="core.system",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_punch_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Punch Item",
                "verbose_name_plural": "Punch Items",
                "ordering": ["category", "-raised_date"],
            },
        ),
        migrations.CreateModel(
            name="PunchItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="punch_photos/%Y/%m/%d/")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[("BEFORE", "Before"), ("AFTER", "After")],
                        default="BEFORE",
                        max_length=10,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "punch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="commissioning.punchitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punch Item Photo",
                "verbose_name_plural": "Punch Item Photos",
            },
        ),
        migrations.CreateModel(
            name="TestProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("PREC", "Pre-Commissioning Test"),
                            ("COLD", "Cold Commissioning Test"),
                            ("HOT", "Hot Commissioning Test"),
                            ("PERF", "Performance Test"),
                            ("FUNC", "Functional Test"),
                            ("SAFE", "Safety System Test"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commissioning_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_procedures",
                        to="commissioning.commissioningsystem",
                    ),
                ),
                (
                    "equipment_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="test_procedures",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Test procedures that must be completed before this one",
                        to="commissioning.testprocedure",
                    ),
                ),
                (
                    "procedure_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_procedures",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Procedure",
                "verbose_name_plural": "Test Procedures",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_number",
                    models.PositiveIntegerField(default=1, help_text="Attempt number"),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("COND", "Conditional Pass"),
                            ("FAIL", "Fail"),
                            ("IPRO", "In Progress"),
                        ],
                        default="IPRO",
                        max_length=4,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="test_signatures/%Y/%m/%d/"
                    ),
                ),
                (
                    "witnessed_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="test_signatures/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_records",
                        to="commissioning.testprocedure",
                    ),
                ),
                (
                    "witnessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witnessed_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Record",
                "verbose_name_plural": "Test Records",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.AddField(
            model_name="punchitem",
            name="test_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="punch_items",
                to="commissioning.testrecord",
            ),
        ),
    ]
