"""
Django settings for kmes project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*ll)hvkwg33kjuf#&a_!0!kg66s=1bxh8#k#%_%o$ht7)nkh+u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CSRF_TRUSTED_ORIGINS = [
    'https://kmes-production.up.railway.app',
    'https://*.up.railway.app',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = [
		'localhost',
		'127.0.0.1',
		'192.168.1.2',  # Your computer's IP address
		'192.168.1.3',  # Your computer's IP address
		'192.168.1.4',  # Your computer's IP address
		'192.168.1.*',    # Allow all devices on this subnet
		'10.0.0.*',
		'*',
		'kmes-production.up.railway.app',
	    '.up.railway.app',   # leading dot = wildcard subdomains
		]

# Application definition

INSTALLED_APPS = [
		"django.contrib.admin",
		"django.contrib.auth",
		"django.contrib.contenttypes",
		"django.contrib.sessions",
		"django.contrib.messages",
		"django.contrib.staticfiles",
		"openpyxl",
		'accounts',
		'core',
		'documents',
		'procurement',
		'construction',
		'commissioning',
		'resources',
		]

MIDDLEWARE = [
		'whitenoise.middleware.WhiteNoiseMiddleware',
		"django.middleware.security.SecurityMiddleware",
		"django.contrib.sessions.middleware.SessionMiddleware",
		"django.middleware.common.CommonMiddleware",
		"django.middleware.csrf.CsrfViewMiddleware",
		"django.contrib.auth.middleware.AuthenticationMiddleware",
		"django.contrib.messages.middleware.MessageMiddleware",
		"django.middleware.clickjacking.XFrameOptionsMiddleware",
		]

ROOT_URLCONF = "kmes.urls"
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = [
		{
				"BACKEND":  "django.template.backends.django.DjangoTemplates",
				"DIRS":     [BASE_DIR / "templates"],
				"APP_DIRS": True,
				"OPTIONS":  {
						"context_processors": [
								"django.template.context_processors.request",
								"django.contrib.auth.context_processors.auth",
								"django.contrib.messages.context_processors.messages",
								'kmes.context_processors.notifications_processor',
								],
						},
				},
		]

WSGI_APPLICATION = "kmes.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
		'default': dj_database_url.config(conn_max_age=600, default='sqlite:///db.sqlite3')
		# "default": {
		# 		"ENGINE": "django.db.backends.sqlite3",
		# 		"NAME":   BASE_DIR / "db.sqlite3",
		# 		}
		}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
		{
				"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
				},
		{
				"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
				},
		{
				"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
				},
		{
				"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
				},
		]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

SITE_LANG = 'fa'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
		os.path.join(BASE_DIR, 'static'),
		]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# For file uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Login/Logout redirect URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Session settings (optional)
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days
SESSION_SAVE_EVERY_REQUEST = True
