# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DWG", "Drawing"),
                            ("PNID", "P&ID"),
                            ("DATA", "Datasheet"),
                            ("MAN", "Manual"),
                            ("PROC", "Procedure"),
                            ("SPEC", "Specification"),
                            ("CERT", "Certificate"),
                            ("RPT", "Report"),
                            ("CALC", "Calculation"),
                            ("OTHR", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("MECH", "Mechanical"),
                            ("ELEC", "Electrical"),
                            ("PIPE", "Piping"),
                            ("INSTR", "Instrumentation"),
                            ("CIVL", "Civil"),
                            ("STRU", "Structural"),
                            ("PROC", "Process"),
                            ("GEN", "General"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        help_text="e.g., 'Rev B', 'IFC', 'A'", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVW", "Under Review"),
                            ("APPR", "Approved"),
                            ("IFC", "Issued for Construction"),
                            ("ASBL", "As-Built"),
                            ("SUPD", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "dwg",
                                    "dxf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Alternative path to document if not uploaded directly",
                        max_length=500,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["document_number", "-revision"],
            },
        ),
        migrations.CreateModel(
            name="TagDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        default="references",
                        help_text="e.g., 'references', 'defines', 'specifies'",
                        max_length=50,
                    ),
                ),
                ("added_date", models.DateField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_documents",
                        to="documents.document",
                    ),
                ),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_documents",
                        to="core.equipmenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag Document Relationship",
                "verbose_name_plural": "Tag Document Relationships",
                "unique_together": {("equipment_tag", "document")},
            },
        ),
    ]
