# Generated by Django 6.0.6 on 2026-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
