# Generated by Django 6.0.6 on 2026-06-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g., 'CU-PH2'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("target_completion_date", models.DateField()),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INIT", "Initiation"),
                            ("PLAN", "Planning"),
                            ("EXEC", "Execution"),
                            ("COMM", "Commissioning"),
                            ("CLSD", "Closed"),
                        ],
                        default="INIT",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ["code"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "System",
                "verbose_name_plural": "Systems",
                "ordering": ["code"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.CreateModel(
            name="EquipmentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_number", models.CharField(db_index=True, max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("CRUSH", "Crusher"),
                            ("CONV", "Conveyor"),
                            ("FLOT", "Flotation Cell"),
                            ("PUMP", "Pump"),
                            ("MOTOR", "Motor"),
                            ("INST", "Instrument"),
                            ("CABLE", "Cable"),
                            ("XFMR", "Transformer"),
                            ("VALV", "Valve"),
                            ("TANK", "Tank"),
                            ("SCRN", "Screen"),
                            ("FEED", "Feeder"),
                            ("CYCL", "Cyclone"),
                            ("THCK", "Thickener"),
                            ("FILT", "Filter"),
                            ("COMP", "Compressor"),
                            ("OTHR", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("MECH", "Mechanical"),
                            ("ELEC", "Electrical"),
                            ("PIPE", "Piping"),
                            ("INSTR", "Instrumentation"),
                            ("CIVL", "Civil"),
                            ("STRU", "Structural"),
                        ],
                        max_length=5,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "criticality",
                    models.CharField(
                        choices=[("HIGH", "High"), ("MED", "Medium"), ("LOW", "Low")],
                        default="MED",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineering"),
                            ("PROC", "Procured"),
                            ("DLVD", "Delivered"),
                            ("INST", "Installed"),
                            ("ALGN", "Aligned"),
                            ("PREC", "Pre-Commissioned"),
                            ("COMM", "Commissioned"),
                            ("HNDO", "Handed Over"),
                            ("DEF", "Defective"),
                        ],
                        default="ENG",
                        max_length=4,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="LxWxH in mm, e.g., '3000x2000x1500'",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_tags",
                        to="core.area",
                    ),
                ),
                (
                    "parent_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_tags",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_tags",
                        to="core.project",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_tags",
                        to="core.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Tag",
                "verbose_name_plural": "Equipment Tags",
                "ordering": ["tag_number"],
                "indexes": [
                    models.Index(
                        fields=["project", "tag_number"],
                        name="core_equipm_project_f4b1b4_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="core_equipm_project_f65a38_idx",
                    ),
                    models.Index(
                        fields=["parent_tag"], name="core_equipm_parent__ddd583_idx"
                    ),
                ],
            },
        ),
    ]
