# Generated by Django 6.0.6 on 2026-07-13 16:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("STORE", "Storage/Warehouse"),
                            ("INST", "Installation Site"),
                            ("WORK", "Workshop"),
                            ("TRANS", "In Transit"),
                            ("TEMP", "Temporary Location"),
                            ("OTHER", "Other"),
                        ],
                        default="INST",
                        max_length=5,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude in decimal degrees (e.g., -23.550520)",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude in decimal degrees (e.g., -46.633308)",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Elevation in meters above sea level",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS accuracy in meters",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True,
                        help_text="Building or structure name",
                        max_length=100,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, help_text="Floor level", max_length=50
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, help_text="Room number or name", max_length=50
                    ),
                ),
                (
                    "grid_reference",
                    models.CharField(
                        blank=True, help_text="Site grid reference", max_length=50
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address or description"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the current location of the equipment?",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Has this location been verified?"
                    ),
                ),
                (
                    "arrival_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the equipment arrived at this location",
                    ),
                ),
                (
                    "departure_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the equipment left this location",
                        null=True,
                    ),
                ),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_locations",
                        to="core.area",
                    ),
                ),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Location",
                "verbose_name_plural": "Equipment Locations",
                "ordering": ["-arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentLocationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Photo of the equipment at this location",
                        upload_to="equipment_locations/%Y/%m/%d/",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("GEN", "General View"),
                            ("CLOSE", "Close-up"),
                            ("SURR", "Surrounding Area"),
                            ("INST", "Installation Detail"),
                            ("DAMG", "Damage/Deterioration"),
                            ("GPS", "GPS Screenshot"),
                            ("SURV", "Survey Mark"),
                            ("OTHER", "Other"),
                        ],
                        default="GEN",
                        max_length=5,
                    ),
                ),
                (
                    "taken_date",
                    models.DateTimeField(
                        blank=True, help_text="When the photo was taken", null=True
                    ),
                ),
                (
                    "direction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Compass direction in degrees (0-360)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.equipmentlocation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_location_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Location Image",
                "verbose_name_plural": "Equipment Location Images",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="equipmentlocation",
            index=models.Index(
                fields=["equipment_tag", "is_current"],
                name="core_equipm_equipme_ad979d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentlocation",
            index=models.Index(
                fields=["latitude", "longitude"], name="core_equipm_latitud_db1f2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentlocation",
            index=models.Index(
                fields=["location_type"], name="core_equipm_locatio_522474_idx"
            ),
        ),
    ]
