# Generated by Django 6.0.6 on 2026-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_equipmenttag_equipment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("Farsi", "فارسی"), ("Enlish", "english")],
                        default="Farsi",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Settings",
                "verbose_name_plural": "Profiles Settings",
            },
        ),
    ]
