# Generated by Django 6.0.6 on 2026-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_equipmenttag_drawing_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttag",
            name="weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
