# Generated by Django 6.0.6 on 2026-08-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_equipmenttag_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttag",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("CRUSH", "Crusher"),
                    ("CONV", "Conveyor"),
                    ("FLOT", "Flotation Cell"),
                    ("PUMP", "Pump"),
                    ("MOTOR", "Motor"),
                    ("INST", "Instrument"),
                    ("CABLE", "Cable"),
                    ("XFMR", "Transformer"),
                    ("VALV", "Valve"),
                    ("TANK", "Tank"),
                    ("SCRN", "Screen"),
                    ("FEED", "Feeder"),
                    ("CYCL", "Cyclone"),
                    ("THCK", "Thickener"),
                    ("FILT", "Filter"),
                    ("COMP", "Compressor"),
                    ("CR", "Crane"),
                    ("SCNW", "Screw Nut Washer"),
                    ("OTHR", "Other"),
                ],
                max_length=5,
            ),
        ),
    ]
