# Generated by Django 6.0.6 on 2026-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_equipmenttag_equipment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmenttag",
            name="installation_order",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
