# Generated by Django 6.0.6 on 2026-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_equipmenttag_installation_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttag",
            name="installation_order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
