# Generated by Django 6.0.6 on 2026-08-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_equipmenttag_installation_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmenttag",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code for this equipment tag",
                null=True,
                upload_to="equipment_qr_codes/",
            ),
        ),
        migrations.AddField(
            model_name="equipmenttag",
            name="qr_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
