# Generated by Django 6.0.6 on 2026-08-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_equipmenttag_qr_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("url", models.CharField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, default=6000, null=True)),
                ("height", models.IntegerField(blank=True, default=4242, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrawingHotSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top", models.IntegerField(blank=True, null=True)),
                ("left", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, default=215, null=True)),
                ("height", models.IntegerField(blank=True, default=65, null=True)),
                (
                    "Drawing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hot_spots",
                        to="core.drawing",
                    ),
                ),
            ],
        ),
    ]
