# Generated by Django 6.0.6 on 2026-08-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_drawing_drawinghotspot"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawinghotspot",
            name="equipment_tag_ID",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
