# Generated by Django 6.0.6 on 2026-08-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_drawinghotspot_equipment_tag_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drawinghotspot",
            old_name="Drawing",
            new_name="drawing",
        ),
    ]
