# Generated by Django 6.0.6 on 2026-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_drawing_drawinghotspot_drawing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawinghotspot",
            name="height",
            field=models.IntegerField(blank=True, default=35, null=True),
        ),
        migrations.AlterField(
            model_name="drawinghotspot",
            name="width",
            field=models.IntegerField(blank=True, default=192, null=True),
        ),
    ]
