# Generated by Django 6.0.6 on 2026-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_drawinghotspot_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmenttag",
            name="packing_list_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
