# Generated by Django 6.0.6 on 2026-08-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_equipmenttag_packing_list_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "packing_list_num",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="equipmenttag",
            name="packing_list_num",
        ),
        migrations.AddField(
            model_name="equipmenttag",
            name="packing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_tags",
                to="core.packinglist",
            ),
        ),
    ]
