# Generated by Django 6.0.6 on 2026-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_packinglist_remove_equipmenttag_packing_list_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code for this equipment tag",
                null=True,
                upload_to="equipment_qr_codes/",
            ),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="qr_code_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
