# Generated by Django 6.0.6 on 2026-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_packinglist_qr_code_packinglist_qr_code_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglist",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="packinglist",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="packinglist",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code for this packing list",
                null=True,
                upload_to="packing_list_qr_codes/",
            ),
        ),
    ]
