# Generated by Django 6.0.6 on 2026-09-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_packinglist_description_packinglist_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                ("discipline", models.CharField(blank=True, max_length=255, null=True)),
                ("page_no", models.IntegerField(blank=True, null=True)),
                (
                    "goods_item_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type_of_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                ("mrs_no", models.CharField(blank=True, max_length=255, null=True)),
                ("mrs_date", models.DateField(blank=True, null=True)),
                ("qty_opi", models.IntegerField(blank=True, null=True)),
                ("miv", models.IntegerField(blank=True, null=True)),
                (
                    "equipment_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_tag",
                        to="core.equipmenttag",
                    ),
                ),
                (
                    "packing_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packing_list",
                        to="core.packinglist",
                    ),
                ),
            ],
        ),
    ]
