# Generated by Django 6.0.6 on 2026-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_packinglistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="packinglistitem",
            name="total_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
