# Generated by Django 6.0.6 on 2026-09-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_packinglistitem_total_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmenttag",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="equipmenttag",
            name="discipline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MECH", "Mechanical"),
                    ("ELEC", "Electrical"),
                    ("PIPE", "Piping"),
                    ("INSTR", "Instrumentation"),
                    ("CIVL", "Civil"),
                    ("STRU", "Structural"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttag",
            name="equipment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRUSH", "Crusher"),
                    ("CONV", "Conveyor"),
                    ("FLOT", "Flotation Cell"),
                    ("PUMP", "Pump"),
                    ("MOTOR", "Motor"),
                    ("INST", "Instrument"),
                    ("CABLE", "Cable"),
                    ("XFMR", "Transformer"),
                    ("VALV", "Valve"),
                    ("TANK", "Tank"),
                    ("SCRN", "Screen"),
                    ("FEED", "Feeder"),
                    ("CYCL", "Cyclone"),
                    ("THCK", "Thickener"),
                    ("FILT", "Filter"),
                    ("COMP", "Compressor"),
                    ("CR", "Crane"),
                    ("SCNW", "Screw Nut Washer"),
                    ("OTHR", "Other"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="equipmenttag",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_tags",
                to="core.project",
            ),
        ),
    ]
