# Generated by Django 6.0.6 on 2026-09-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_equipmenttag_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packinglistitem",
            name="equipment_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_list_items",
                to="core.equipmenttag",
            ),
        ),
        migrations.AlterField(
            model_name="packinglistitem",
            name="packing_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packing_list_items",
                to="core.packinglist",
            ),
        ),
    ]
