# Generated by Django 6.0.6 on 2026-09-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_packinglistitem_equipment_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grid_x", models.CharField(blank=True, max_length=255, null=True)),
                ("grid_y", models.CharField(blank=True, max_length=255, null=True)),
                ("grid_z", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
