# Generated by Django 6.0.6 on 2026-09-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_equipmentgrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentgrid",
            name="equipment_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grids",
                to="core.equipmenttag",
            ),
        ),
    ]
